package utilities

import (
	"context"
	"fmt"
	"log"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
	"go.mongodb.org/mongo-driver/mongo/readpref"

	"encoding/json"
	"net/http"
)

func ConnetMongo() {
	localConnectStr := "mongodb://localhost:27017/?readPreference=primary&ssl=false"
	client, err := mongo.NewClient(options.Client().ApplyURI(
		// remoteConnectStr,
		localConnectStr,
	))
	if err != nil {
		log.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	err = client.Connect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Disconnect(ctx)

	err = client.Ping(ctx, readpref.Primary())
	if err != nil {
		log.Fatal(err)
	}

	databases, err := client.ListDatabaseNames(ctx, bson.M{})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(databases)

	db := client.Database("local")
	collection := db.Collection("startup_log")
	cursor, err := collection.Find(ctx, bson.M{"_id": "ubuntu-1615493216307"})
	if err != nil {
		log.Fatal(err)
	}
	defer cursor.Close(ctx)
	for cursor.Next(ctx) {
		var row bson.M
		if err = cursor.Decode(&row); err != nil {
			log.Fatal(err)
		}
		fmt.Println(row["hostname"], " : ", row["cmdLine"])
		fmt.Println("---------------------")
		break
	}
}

func Double(a int) int {
	return a * 2
}

func ConnetFinnhub() {

	client := http.Client{}
	patternRecognition := "https://finnhub.io/api/v1/scan/pattern?symbol=TSLA&resolution=D&token=c17bkh748v6se55vr9eg"
	// signalRecommand := "https://finnhub.io/api/v1/stock/recommendation?symbol=TSLA&token=c17bkh748v6se55vr9eg"

	//https://mholt.github.io/json-to-go/
	// type Autogenerated_Signal []struct {
	// 	Buy        int    `json:"buy"`
	// 	Hold       int    `json:"hold"`
	// 	Period     string `json:"period"`
	// 	// Period     time.Time	
	// 	Sell       int    `json:"sell"`
	// 	Strongbuy  int    `json:"strongBuy"`
	// 	Strongsell int    `json:"strongSell"`
	// 	Symbol     string `json:"symbol"`
	// }

	type Autogenerated struct {
		Points []struct {
			Aprice      float64 `json:"aprice"`
			Atime       int     `json:"atime"`
			Bprice      float64 `json:"bprice,omitempty"`
			Btime       int     `json:"btime,omitempty"`
			Cprice      float64 `json:"cprice,omitempty"`
			Ctime       int     `json:"ctime,omitempty"`
			Dprice      float64 `json:"dprice"`
			Dtime       int     `json:"dtime"`
			Entry       float64 `json:"entry,omitempty"`
			EntryDate   int     `json:"entry_date,omitempty"`
			Eprice      float64 `json:"eprice,omitempty"`
			Etime       int     `json:"etime,omitempty"`
			Mature      int     `json:"mature"`
			Patternname string  `json:"patternname"`
			Patterntype string  `json:"patterntype"`
			Profit1     int     `json:"profit1,omitempty"`
			Profit2     float64 `json:"profit2,omitempty"`
			Sorttime    int     `json:"sortTime"`
			Status      string  `json:"status"`
			Stoploss    float64 `json:"stoploss,omitempty"`
			Symbol      string  `json:"symbol"`
			Terminal    int     `json:"terminal,omitempty"`
			EndPrice    float64 `json:"end_price,omitempty"`
			EndTime     int     `json:"end_time,omitempty"`
			StartPrice  float64 `json:"start_price,omitempty"`
			StartTime   int     `json:"start_time,omitempty"`
		} `json:"points"`
	}

	request, err := http.NewRequest("GET", patternRecognition, nil)
	if err != nil {
		fmt.Println(err)
	}

	resp, err := client.Do(request)
	if err != nil {
		fmt.Println(err)
	}

	// var result map[string]Autogenerated
	var result Autogenerated

	json.NewDecoder(resp.Body).Decode(&result)
	// fmt.Println(result)

	for _, v := range result.Points {
		unixTimeUTC := time.Unix(int64(v.Atime), 0) //gives unix time stamp in utc 
		// asDate, _ := time.Parse(time.ANSIC, unixTimeUTC.UTC().String())
		fmt.Println("Symbol:", v.Symbol, " patternname: ", v.Patternname, " patterntype: ", v.Patterntype, " time: ", unixTimeUTC.UTC().String())
	  }

	// servalDaysAgo := time.Now().AddDate(0, 0, -100)

	// for _, v := range result {
	// 	asDate, _ := time.Parse("2006-01-02", v.Period)
	// 	// asDate, _ := time.Parse(time.ANSIC, v.Period)
	// 	if asDate.After(servalDaysAgo){
	// 		fmt.Println("Symbol:", v.Symbol, " buy: ", v.Buy, " period: ", v.Period, 
	// 		" as Date: ", asDate)
	
	// 	}
	// }


}
